### ISSUE TITLE
Plugin fails to process layers after encountering complex SQL view layers

### ISSUE THREAD

**Issue by bbscout** [enricofer/changeDataSource#21]
Description:
When working with multiple PostGIS layers in QGIS project, the plugin stops processing layers at the point where it encounters layers based on complex SQL views (WITH clause, window functions, etc.). 

Steps to reproduce:
1. Create a QGIS project with mixture of:
   - Regular PostGIS layers (table-based)
   - PostGIS layers based on complex SQL views (using WITH clause, window functions, ST_Buffer, etc.)
2. Open changeDataSource plugin
3. Try to change datasource for all layers

Current behavior:
- Plugin only shows and processes layers up to the first SQL view layer
- When trying to process selected layers after SQL view layer, it throws error:

```
Traceback (most recent call last):
File ".../changeDataSource.py", line 385, in replaceDS
scope.setFeature(next(self.layersPropLayer.getFeatures(QgsFeatureRequest(row+1))))
StopIteration
```
Expected behavior:
- Plugin should either:
a) Handle SQL view layers correctly, or
b) Skip SQL view layers but continue processing subsequent layers, or
c) Show clear warning that SQL view layers are not supported

Example of problematic layer source:
```sql
table="(SELECT row_number() OVER () AS fid, * FROM ( WITH dissolved AS (...) SELECT ..., ST_Buffer((ST_Dump(merged_geom)).geom,0) AS geom FROM dissolved) AS _subq_1_)"
```

Environment:

QGIS version: 3.34.0-Prizren
Plugin version: 3.1
OS: Windows 10

**Comment by santonetti** [comment]
@bbscout Hello,
I think I have an idea of what the issue comes from.

```
Traceback (most recent call last):
File ".../changeDataSource.py", line 385, in replaceDS
scope.setFeature(next(self.layersPropLayer.getFeatures(QgsFeatureRequest(row+1))))
StopIteration
```

I also encountered this same issue when having a bit subset on a layer. The change in datasource was working for all layers until the layer with this big subset.

This issue came from the fact that the display field on the widget for the datasource is limited to 250 character in total. Your request is then truncated to this limit and thus the error may comes from an incorrect because incomplete SQL truncated request.

You can solve this issue by fixing the limit of the character inside the code directly :
file : .../AppData\Roaming\QGIS\QGIS3\profiles\default\python\plugins\changeDataSource.py
line 258 : 
`layersPropLayerDef = "Point?crs=epsg:3857&field=layerid:string(200)&field=layername:string(200)&field=layertype:string(20)&field=geometrytype:string(20)&field=provider:string(20)&field=datasource:string(250)&field=authid:string(20)"`

Change value `field=datasource:string(250)` to `field=datasource:string(1500)` for instance. It solved my issue.
